### PR TITLE
Fix OPTIONS request for not found routes

### LINKED ISSUE #72: OPTIONS not found path was throw an error
Originally reported by @Moln in zendframework/zend-expressive-skeleton#245

Request `OPTIONS /not-found-action`

Throw an error:

```
ErrorException: implode(): Invalid arguments passed in file D:\www\frameworks\ze3\vendor\zendframework\zend-expressive-router\src\Middleware\ImplicitOptionsMiddleware.php on line 84
Stack trace:
  1. ErrorException->() D:\www\frameworks\ze3\vendor\zendframework\zend-expressive-router\src\Middleware\ImplicitOptionsMiddleware.php:84
  2. implode() D:\www\frameworks\ze3\vendor\zendframework\zend-expressive-router\src\Middleware\ImplicitOptionsMiddleware.php:84
  3. Zend\Expressive\Router\Middleware\ImplicitOptionsMiddleware->process() D:\www\frameworks\ze3\vendor\zendframework\zend-expressive\src\Middleware\LazyLoadingMiddleware.php:46
  4. Zend\Expressive\Middleware\LazyLoadingMiddleware->process() D:\www\frameworks\ze3\vendor\zendframework\zend-stratigility\src\MiddlewarePipe.php:78
  5. Zend\Stratigility\MiddlewarePipe->handle() D:\www\frameworks\ze3\vendor\zendframework\zend-expressive-router\src\Middleware\ImplicitHeadMiddleware.php:84
  6. Zend\Expressive\Router\Middleware\ImplicitHeadMiddleware->process() D:\www\frameworks\ze3\vendor\zendframework\zend-expressive\src\Middleware\LazyLoadingMiddleware.php:46
  7. Zend\Expressive\Middleware\LazyLoadingMiddleware->process() D:\www\frameworks\ze3\vendor\zendframework\zend-stratigility\src\MiddlewarePipe.php:78
  8. Zend\Stratigility\MiddlewarePipe->handle() D:\www\frameworks\ze3\vendor\zendframework\zend-expressive-router\src\Middleware\RouteMiddleware.php:54
  9. Zend\Expressive\Router\Middleware\RouteMiddleware->process() D:\www\frameworks\ze3\vendor\zendframework\zend-expressive\src\Middleware\LazyLoadingMiddleware.php:46
 10. Zend\Expressive\Middleware\LazyLoadingMiddleware->process() D:\www\frameworks\ze3\vendor\zendframework\zend-stratigility\src\MiddlewarePipe.php:78
 11. Zend\Stratigility\MiddlewarePipe->handle() D:\www\frameworks\ze3\vendor\zendframework\zend-expressive-helpers\src\ServerUrlMiddleware.php:37
 12. Zend\Expressive\Helper\ServerUrlMiddleware->process() D:\www\frameworks\ze3\vendor\zendframework\zend-expressive\src\Middleware\LazyLoadingMiddleware.php:46
 13. Zend\Expressive\Middleware\LazyLoadingMiddleware->process() D:\www\frameworks\ze3\vendor\zendframework\zend-stratigility\src\MiddlewarePipe.php:78
 14. Zend\Stratigility\MiddlewarePipe->handle() D:\www\frameworks\ze3\vendor\zendframework\zend-stratigility\src\Middleware\ErrorHandler.php:143
 15. Zend\Stratigility\Middleware\ErrorHandler->process() D:\www\frameworks\ze3\vendor\zendframework\zend-expressive\src\Middleware\LazyLoadingMiddleware.php:46
 16. Zend\Expressive\Middleware\LazyLoadingMiddleware->process() D:\www\frameworks\ze3\vendor\zendframework\zend-stratigility\src\MiddlewarePipe.php:78
 17. Zend\Stratigility\MiddlewarePipe->handle() D:\www\frameworks\ze3\vendor\zendframework\zend-httphandlerrunner\src\RequestHandlerRunner.php:95
 18. Zend\HttpHandlerRunner\RequestHandlerRunner->run() D:\www\frameworks\ze3\vendor\zendframework\zend-expressive\src\Application.php:81
 19. Zend\Expressive\Application->run() D:\www\frameworks\ze3\public\index.php:29
 20. {closure}() D:\www\frameworks\ze3\public\index.php:30
```

### Expected results

Response 404 status.

### Actual results

Throw an error.

### PR DESCRIPTION
**Pull request by webimpress**
Pass to next handler when route is not matched.

Fixes #72 

- [x] Are you fixing a bug?
  - [x] Detail how the bug is invoked currently.
  - [x] Detail the original, incorrect behavior.
  - [x] Detail the new, expected behavior.
  - [x] Base your feature on the `master` branch, and submit against that branch.
  - [x] Add a regression test that demonstrates the bug, and proves the fix.
  - [ ] Add a `CHANGELOG.md` entry for the fix.

### CODE REVIEW

File: test/Middleware/ImplicitOptionsMiddlewareTest.php [hunk 1]
```diff
@@ -73,12 +73,11 @@ public function testReturnsResultOfHandlerWhenRouteSupportsOptionsExplicitly()
     {
         $route = $this->prophesize(Route::class);
 
-        $result = $this->prophesize(RouteResult::class);
-        $result->getMatchedRoute()->will([$route, 'reveal']);
+        $result = RouteResult::fromRoute($route->reveal());
```
Comment (webimpress) [inline test/Middleware/ImplicitOptionsMiddlewareTest.php]: Changed here to **not** mocking the RouteResult because if we use more methods we need always extend our mock.
And what's more we can easily mock `RouteResult` wrong way. We can create new instance only by using `fromRoute` or `fromRouteFailure` but we can create invalid mock as we have to mock 4-5 public methods...

File: test/Middleware/ImplicitOptionsMiddlewareTest.php [hunk 2]
```diff
@@ -93,13 +92,11 @@ public function testInjectsAllowHeaderInResponseProvidedToConstructorDuringOptio
     {
         $allowedMethods = [RequestMethod::METHOD_GET, RequestMethod::METHOD_POST];
 
-        $result = $this->prophesize(RouteResult::class);
-        $result->getAllowedMethods()->willReturn($allowedMethods);
-        $result->getMatchedRoute()->willReturn(false);
+        $result = RouteResult::fromRouteFailure($allowedMethods);
```
Comment (webimpress) [inline test/Middleware/ImplicitOptionsMiddlewareTest.php]: The same comment here as above about mocking `RouteResult`.

File: test/Middleware/ImplicitOptionsMiddlewareTest.php [hunk 3]
```diff
@@ -111,4 +108,21 @@ public function testInjectsAllowHeaderInResponseProvidedToConstructorDuringOptio
         $result = $this->middleware->process($request->reveal(), $handler->reveal());
         $this->assertSame($this->response->reveal(), $result);
     }
+
+    public function testReturnsResultOfHandlerWhenRouteNotFound()
+    {
+        $result = RouteResult::fromRouteFailure(Route::HTTP_METHOD_ANY);
```
Comment (webimpress) [inline test/Middleware/ImplicitOptionsMiddlewareTest.php]: This is the main test, so in case route NOT FOUND we have allowed any methods, but the result is failure.
So `isFailure === true` and `isMethodFailure === false`. Then -> 404.

**Comment by weierophinney** [comment]
Thanks, @webimpress!
